# Enable plugin debugging (warning: this is very verbose!)
debug: false

# Define the messages used for birthday events
# Leave any message empty ('') to disable it
#   announcement: The broadcast message used when the player joins
#   gift: The message to send to the player when they receive their gift    
#   join: The player's login message will be changed to this message on their birthday
messages:
  join: '&e<PLAYER> joined the game.. and it''s their &cbirthday &etoday!'
  announcement: '&b-=-=-=- Please wish a &9Happy Birthday &bto <PLAYER> -=-=-=-'
  claim: '&dYou have received birthday gift(s)! Type &b/bgift claim'
  gift: '&aWe hope you like your special birthday gifts!'
  money: '&aYou have been given &e$<MONEY>'

# How much money to award the player on their birthday
# Set to 0 to disable 
money: 1000

# Which items to give to the player on their birthday
# Leave list empty to disable
# Format is: <ITEM>[,AMOUNT]
# (NOTE: ITEM can be ITEM ID or ITEM NAME, and can also include a data value)
#
# Examples:
#   - CAKE
#   - 357,2
#   - GOLDEN_APPLE:1,1
#   - DIAMONDSWORD,1
#   - DIAMOND,5
items:
  - CAKE
  - GOLDEN_APPLE:1,1
  - COOKIE,2
  - DIAMOND,5
  - EMERALD,5
  - BEACON,1
