name: BirthdayGift
main: au.com.addstar.birthdaygift.BirthdayGift
version: 0.0.3
author: add5tar
description: Allow users to set their birthday and receive gifts on their birthday

commands:
  birthday:
    description: Set or view your birthday (to receive birthday gifts)
  bgift:
    aliases: birthdaygift
    description: Additional BirthdayGift commands