name: BirthdayGift
main: au.com.addstar.birthdaygift.BirthdayGift
version: 1.1.0
author: add5tar
load-after: Vault
website: http://dev.bukkit.org/server-mods/birthdaygift/
dev-url: http://dev.bukkit.org/server-mods/birthdaygift/
description: Reward players on their birthday and notify everyone of the player's birthday

commands:
  birthday:
    description: Set or view your birthday (to receive birthday gifts)
  bgift:
    aliases: birthdaygift
    description: Additional BirthdayGift commands
    
permissions:
  birthdaygift.*:
    description: Full access to all commands (admin)
    children:
      birthdaygift.use: true
      birthdaygift.claim: true
      birthdaygift.info: true
      birthdaygift.stats: true
      birthdaygift.set: true
      birthdaygift.reset: true
      birthdaygift.delete: true
    default: op
  birthdaygift.use:
    description: Allow use of the /birthday command
    default: true
  birthdaygift.claim:
    description: Allow use of the /bgift claim command (to allow claiming only in specific worlds)
    default: true
  birthdaygift.info:
    description: Allow access to the /bgift info command
    default: op 
  birthdaygift.stats:
    description: Allow access to the /bgift stats command
    default: op 
  birthdaygift.set:
    description: Allow access to the /bgift set command
    default: op 
  birthdaygift.reset:
    description: Allow access to the /bgift reset command
    default: op 
  birthdaygift.delete:
    description: Allow access to the /bgift delete command
    default: op 
      